// whole array

export const resList = [
  {
    info: {
      id: "1",
      name: "Chandralok Kachouri",
      cloudinaryImageId: "qbo11lh7l43xpkd7wqts",
      costForTwo: "₹150 for two",
      cuisines: ["Snacks", "South Indian", "Chinese", "Fast Food", "Pizzas"],
      avgRating: 4,
      sla: { slaString: "25 MINS" },
    },
  },
  {
    info: {
      id: "2",
      name: "Jai Shree Shankar Punjabi Dhaba",
      cloudinaryImageId: "slfbprrckr7jk1zm58rd",
      costForTwo: "₹250 for two",
      cuisines: [
        "Indian",
        "North Indian",
        "Chinese",
        "South Indian",
        "Snacks",
        "Punjabi",
        "Beverages",
      ],
      avgRating: 3.6,
      sla: { slaString: "30 MINS" },
    },
  },
  {
    info: {
      id: "3",
      name: "Statesman House",
      cloudinaryImageId: "98588793791dd32f2daa7e3595fcb69c",
      costForTwo: "₹300 for two",
      cuisines: ["North Indian", "Chinese"],
      avgRating: 3.8,
      sla: { slaString: "28 MINS" },
    },
  },
  {
    info: {
      id: "4",
      name: "The Quick Curry",
      cloudinaryImageId: "aq5uredkyfrmct6a99cv",
      costForTwo: "₹250 for two",
      cuisines: ["Thalis", "North Indian"],
      avgRating: 3.8,
      sla: { slaString: "32 MINS" },
    },
  },
  {
    info: {
      id: "5",
      name: "Fire House Pizza",
      cloudinaryImageId: "906c0affa7d8ff78a3e4db88b4433cde",
      costForTwo: "₹600 for two",
      cuisines: ["Pizzas"],
      avgRating: 3.6,
      sla: { slaString: "35 MINS" },
    },
  },
  {
    info: {
      id: "6",
      name: "Al-Baik Zone",
      cloudinaryImageId: "mra2lrsmgduhwswzzee0",
      costForTwo: "₹200 for two",
      cuisines: ["Fast Food", "Arabian", "Biryani"],
      avgRating: 4,
      sla: { slaString: "27 MINS" },
    },
  },
  {
    info: {
      id: "7",
      name: "Raju Kitchen Restaurant",
      cloudinaryImageId: "u8m5sxxbwuwfjolzdf69",
      costForTwo: "₹200 for two",
      cuisines: [
        "Indian",
        "Chinese",
        "Mughlai",
        "North Indian",
        "Snacks",
        "Lucknowi",
        "Biryani",
      ],
      avgRating: 3.7,
      sla: { slaString: "29 MINS" },
    },
  },
  {
    info: {
      id: "8",
      name: "Momos castle",
      cloudinaryImageId: "lubiprpdt4cgnunga3rr",
      costForTwo: "₹150 for two",
      cuisines: ["Chinese"],
      avgRating: 4.3,
      sla: { slaString: "22 MINS" },
    },
  },
  {
    info: {
      id: "9",
      name: "Delight The Pastry Shop",
      cloudinaryImageId: "dlx59kcbntvnlf8igifw",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery", "Chinese", "Biryani", "Snacks"],
      avgRating: 4.1,
      sla: { slaString: "24 MINS" },
    },
  },
  {
    info: {
      id: "10",
      name: "Jai Shree Shankar Bhojanalaya",
      cloudinaryImageId: "qhdec9rh38ewnb80tkim",
      costForTwo: "₹250 for two",
      cuisines: [
        "North Indian",
        "Thalis",
        "South Indian",
        "Chinese",
        "Snacks",
        "Indian",
      ],
      avgRating: 3.7,
      sla: { slaString: "31 MINS" },
    },
  },
  {
    info: {
      id: "11",
      name: "Aryan Family's Delight",
      cloudinaryImageId: "kb34u4pywk49ksbyn4g5",
      costForTwo: "₹400 for two",
      cuisines: [
        "North Indian",
        "South Indian",
        "Fast Food",
        "Snacks",
        "Burgers",
        "Chinese",
      ],
      avgRating: 4.2,
      sla: { slaString: "26 MINS" },
    },
  },
  {
    info: {
      id: "12",
      name: "Haldiram Bhujiawala",
      cloudinaryImageId: "nkd7purcqzconoypeto9",
      costForTwo: "₹300 for two",
      cuisines: [
        "Sweets",
        "North Indian",
        "South Indian",
        "Chinese",
        "Desserts",
        "Indian",
        "Fast Food",
      ],
      avgRating: 3.7,
      sla: { slaString: "33 MINS" },
    },
  },
  {
    info: {
      id: "13",
      name: "Pizza Club 99",
      cloudinaryImageId: "yxkkxyhgvcb0mkmneoj6",
      costForTwo: "₹300 for two",
      cuisines: ["Pizzas", "Fast Food", "Beverages"],
      avgRating: 3.7,
      sla: { slaString: "30 MINS" },
    },
  },
  {
    info: {
      id: "14",
      name: "Hot Stuff",
      cloudinaryImageId: "beeaadg3lqjics4fzuvw",
      costForTwo: "₹200 for two",
      cuisines: ["North Indian", "Beverages", "Desserts", "Pizzas"],
      avgRating: 3.8,
      sla: { slaString: "23 MINS" },
    },
  },
  {
    info: {
      id: "15",
      name: "Shri Ram Shakahari Bhojnalaya",
      cloudinaryImageId: "suz4we5x7dgznrquxvu9",
      costForTwo: "₹200 for two",
      cuisines: ["North Indian"],
      avgRating: 4.1,
      sla: { slaString: "21 MINS" },
    },
  },
  {
    info: {
      id: "16",
      name: "Urban Tadka",
      cloudinaryImageId: "qbo11lh7l43xpkd7wqts",
      costForTwo: "₹350 for two",
      cuisines: ["North Indian", "Chinese", "Tandoor"],
      avgRating: 4.4,
      sla: { slaString: "27 MINS" },
    },
  },
];
